# debug: true
ymlcfg: 
  projectName: devil13th sys34
#trace=true
# 打开actuator 所有端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
server: 
  port: 8899
  servlet: 
    context-path: /thd
#spring.mvc.view.prefix= /WEB-INF/pages/
#spring.mvc.view.suffix= .jsp


  
      
      
spring:
  #jackson:
    #serialization:
      # 时间格式化格式
      #date-format: yyyy-MM-dd 
      # 时区设置
      #time-zone: GMT+8
      # 是否将日期格式转为时间戳
      #write-dates-as-timestamps: false
  http: 
  encoding: 
    charset: UTF-8
    enabled: true
    force: true
  thymeleaf: 
    cache: false
    prefix: classpath:/template
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: HTML
  devtools: 
    restart: 
      exclude: static/**, public/**,template/** 
  datasource: 
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatistest
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource 
    hikari: 
      #客户端等待连接池连接的最大毫秒数
      connection-timeout: 20000
      #最小空闲连接数
      minimum-idle: 5
      #配置最大池大小
      maximum-pool-size: 12
      #是允许连接在连接池中空闲的最长时间
      idle-timeout: 300000 
      #中连接关闭后的最长生命周期,使用中的连接永远不会退役，只有当它关闭时才会在最长生命周期后删除
      max-lifetime: 1200000
      #从池返回的连接的默认自动提交行为
      autoCommit: true


logging:
  file: mylogs.log
  path: D:/deleteme/mylogs
  level: 
    root: INFO
       
hello: 
  msg: Thirdteendevil
  show: true