<#assign get="${" />

<!--
file autogenerated by ThirdteenDevils's CodeGenUtil 
-->

<!-- ${cfg.tableCodeForClass} service bean -->
<bean id="${cfg.serviceNameForProperty}" class="${cfg.servicePackage}.${cfg.serviceName}Impl" parent="pubService"></bean>

<!-- ${cfg.tableCodeForClass} action bean -->
<bean id="${cfg.actionNameForProperty}" class="${cfg.actionPackage}.${cfg.actionName}" scope="prototype" ></bean>


<!-- ${cfg.tableCodeForClass} struts config -->
<package name="${cfg.tableCodeForProperty}" extends="myDefault" namespace="/${cfg.nameSpace}">
    	<action name="${cfg.urlActionName}" class="${cfg.actionPackage}.${cfg.actionName}">
    		<result>${get}forwardPage}</result>
    	</action>
</package>

