package ${cfg.pojoPackage};

import java.util.Date;

/**
 * ${cfg.pojoPackage}.${cfg.tableCodeForClass} entity. 
 * file autogenerated by ThirdteenDevils's CodeGenUtil
 */

public class ${cfg.tableCodeForClass} implements java.io.Serializable {
	<#--  主键字段      -->
	//PK  ${cfg.pkColumn.columnName} ${cfg.pkColumn.columnDesc}
	private ${cfg.pkColumn.columnType} ${cfg.pkColumn.columnCodeForProperty};
	<#--  非主键字段      -->
<#list cfg.columnList as col> 
	//${col.columnName} ${col.columnDesc}
	private ${col.columnType} ${col.columnCodeForProperty};
</#list>
	
	<#--  主键字段setter getter  -->
	public void set${cfg.pkColumn.columnCodeForClass}(${cfg.pkColumn.columnType} ${cfg.pkColumn.columnCodeForProperty}){
		this.${cfg.pkColumn.columnCodeForProperty} = ${cfg.pkColumn.columnCodeForProperty};
	}
	public ${cfg.pkColumn.columnType} get${cfg.pkColumn.columnCodeForClass}(){
		return this.${cfg.pkColumn.columnCodeForProperty};
	}
	<#--  非主键字段setter getter  -->
<#list cfg.columnList as col> 
	public void set${col.columnCodeForClass}(${col.columnType} ${col.columnCodeForProperty}){
		this.${col.columnCodeForProperty} = ${col.columnCodeForProperty};
	}
	public ${col.columnType} get${col.columnCodeForClass}(){
		return this.${col.columnCodeForProperty};
	}
</#list>
	
	

}