package ${cfg.servicePackage};

import java.util.List;
import java.util.Map;
import ${cfg.pojoPackage}.${cfg.tableCodeForClass};
import com.thd.service.PubService;
import com.thd.util.Page;
/**
 * file autogenerated by ThirdteenDevils's CodeGenUtil 
 */
public interface ${cfg.serviceName} extends PubService {
	/**
	 * 查询${cfg.tableName}列表
	 * @param m 查询条件
	 * @param p 分页信息
	 * @return
	 */
	public List query${cfg.tableCodeForClass}(Map<String,String> m , Page p);
	/**
	 * 保存${cfg.tableName}
	 * @param obj ${cfg.tableName}对象
	 */
	public void save${cfg.tableCodeForClass}(${cfg.tableCodeForClass} obj) ;
	/**
	 * 更新${cfg.tableName}
	 * @param obj ${cfg.tableName}对象
	 */
	public void update${cfg.tableCodeForClass}(${cfg.tableCodeForClass} obj);
	/**
	 * 根据主键查询${cfg.tableName}对象
	 * @param pk 主键
	 */
	public ${cfg.tableCodeForClass} query${cfg.tableCodeForClass}ById(${cfg.pkColumn.columnType} pk);
	/**
	 * 删除${cfg.tableName}对象
	 * @param pk 主键
	 */
	public void delete${cfg.tableCodeForClass}ById(${cfg.pkColumn.columnType} pk);
	/**
	 * 批量删除${cfg.tableName}对象
	 * @param ids 主键,多个主键用","隔开
	 */
	public void delete${cfg.tableCodeForClass}ByIds(String ids);

}
