<#assign get="${" />
/**
 * file autogenerated by ThirdteenDevils's CodeGenUtil  
 * author:thd
 * qq:181907667
 */
=========================================  基础信息  =========================================  
//表英文名 :                                  ${get}cfg.tableCode}:${cfg.tableCode}
//表中文名 :                                   ${get}cfg.tableName}: ${cfg.tableName}
//action 所在包位置 :                          ${get}cfg.actionPackage}:${cfg.actionPackage}
//action 名称 :                                ${get}cfg.actionName}: ${cfg.actionName}
//service 所在包位置 :                         ${get}cfg.servicePackage}:${cfg.servicePackage}
//service 名称 :                               ${get}cfg.serviceName}: ${cfg.serviceName}
//pojo 包所在位置 :                            ${get}cfg.pojoPackage}: ${cfg.pojoPackage}

//jsp页面路径 :                                ${get}cfg.jspPath}: ${cfg.jspPath}
//struts2配置的nameSpace :                     ${get}cfg.nameSpace}: ${cfg.nameSpace}
//struts2配置的action标签的name属性 :          ${get}cfg.urlActionName}:${cfg.urlActionName}
//主键生成策略 :                               ${get}cfg.generator}: ${cfg.generator}
//表类名 :                                     ${get}cfg.tableCodeForClass}: ${cfg.tableCodeForClass}
//表实例化对象名称 :                           ${get}cfg.tableCodeForProperty}: ${cfg.tableCodeForProperty}
//表名全大写 :                                 ${get}cfg.tableCodeForUpper}:${cfg.tableCodeForUpper}
//service实例化对象名称 :                      ${get}cfg.serviceNameForProperty}: ${cfg.serviceNameForProperty}
//action实例化对象名称 :                       ${get}cfg.actionNameForProperty}:${cfg.actionNameForProperty}



=========================================  主键信息  =========================================  
//字段CODE :                                   ${get}cfg.pkColumn.columnCode}: ${cfg.pkColumn.columnCode}
//字段名称 :                                   ${get}cfg.pkColumn.columnName}: ${cfg.pkColumn.columnName}
//字段类型 :                                   ${get}cfg.pkColumn.columnType}:${cfg.pkColumn.columnType}
//字段备注 :                                   ${get}cfg.pkColumn.columnDesc}:${cfg.pkColumn.columnDesc}
//字段名属性 :                                 ${get}cfg.pkColumn.columnCodeForProperty}:${cfg.pkColumn.columnCodeForProperty}
//字段名类名 :                                 ${get}cfg.pkColumn.columnCodeForClass}: ${cfg.pkColumn.columnCodeForClass}
//字段名大写 :                                 ${get}cfg.pkColumn.columnCodeForUpper}: ${cfg.pkColumn.columnCodeForUpper}


=========================================  字段信息  =========================================  
<#list cfg.columnList as col> 
//字段CODE :                                   ${get}col.columnCode}:${col.columnCode}
//字段名称 :                                   ${get}col.columnName}: ${col.columnName}
//字段类型 :                                   ${get}col.columnType}:${col.columnType}
//字段备注 :                                   ${get}col.columnDesc}: ${col.columnDesc}
//字段名属性 :                                 ${get}col.columnCodeForProperty}:${col.columnCodeForProperty}
//字段名类名 :                                 ${get}col.columnCodeForClass}:${col.columnCodeForClass}
//字段名大写 :                                 ${get}col.columnCodeForUpper}: ${col.columnCodeForUpper}
-------------------------------
</#list>




=========================================  生成文件说明 =========================================  


${cfg.tableCodeForClass}.java       放在${cfg.pojoPackage}包下
${cfg.tableCodeForClass}.hbm.xml    放在${cfg.pojoPackage}包下
${cfg.serviceName}.java             放在${cfg.servicePackage}包下
${cfg.serviceName}Impl.java         放在${cfg.servicePackage}包下
${cfg.actionName}.java              放在${cfg.actionPackage}包下
${cfg.tableCodeForProperty}List.jsp 放在WebRoot/${cfg.jspPath}目录下
${cfg.tableCodeForProperty}Form.jsp 放在WebRoot/${cfg.jspPath}目录下

${cfg.tableCodeForProperty}_cfg.xml 内容分别放到struts.xml中和spring配置文件中


=========================================  访问地址 　========================================= 

---列表页
/${get}cfg.nameSpace}/${get}cfg.urlActionName}!${get}cfg.tableCodeForProperty}List.do
/${cfg.nameSpace}/${cfg.urlActionName}!${cfg.tableCodeForProperty}List.do
---列表页获取数据
/${get}cfg.nameSpace}/${get}cfg.urlActionName}!${get}cfg.tableCodeForProperty}ListGetDate.do
/${cfg.nameSpace}/${cfg.urlActionName}!${cfg.tableCodeForProperty}ListGetDate.do
---保存或新增页面
/${get}cfg.nameSpace}/${get}cfg.urlActionName}!${get}cfg.tableCodeForProperty}Form.do
/${cfg.nameSpace}/${cfg.urlActionName}!${cfg.tableCodeForProperty}Form.do
---保存或新增
/${get}cfg.nameSpace}/${get}cfg.urlActionName}!${get}cfg.tableCodeForProperty}FormSubmit.do
/${cfg.nameSpace}/${cfg.urlActionName}!${cfg.tableCodeForProperty}FormSubmit.do



























