package com.thd.common.infrastructure.pojo;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * com.thd.common.infrastructure.pojo.ReactCodegenTest entity. 
 * file autogenerated by ThirdteenDevils's CodeGenUtil
 */
@Entity
@Table(name="react_codegen_test")
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class ReactCodegenTest implements java.io.Serializable {
	//PK  assigned主键
	@Id
	@GenericGenerator(name = "idGeneratorForReactCodegenTest", strategy = "assigned")  
	@GeneratedValue(generator = "idGeneratorForReactCodegenTest")
	@Column(name="test_id" ,length=255)
	private java.lang.String testId;
	
	
	
	
	//字符串
	//varchar
	@Column(name="test_name" ,length=255)
	private java.lang.String testName;
	
	//整数
	//int
	@Column(name="test_int" )
	private java.lang.Integer testInt;
	
	//浮点
	//float
	@Column(name="test_float" )
	private java.lang.Float testFloat;
	
	//数值
	//decimal
	@Column(name="test_decimal" )
	private java.lang.Double testDecimal;
	
	//日期
	//date
	//@Temporal(TemporalType.DATE)
	@JsonFormat(pattern="yyyy-MM-dd",timezone="GMT+8")
	@Column(name="test_date" )
	private java.util.Date testDate;
	
	//日期时间
	//datetime
	@Temporal(TemporalType.TIMESTAMP)
	@JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
	@Column(name="test_datetime" )
	private java.util.Date testDatetime;
	







	
	public void setTestId(java.lang.String testId){
		this.testId = testId;
	}
	public java.lang.String getTestId(){
		return this.testId;
	}
	public void setTestName(java.lang.String testName){
		this.testName = testName;
	}
	public java.lang.String getTestName(){
		return this.testName;
	}
	public void setTestInt(java.lang.Integer testInt){
		this.testInt = testInt;
	}
	public java.lang.Integer getTestInt(){
		return this.testInt;
	}
	public void setTestFloat(java.lang.Float testFloat){
		this.testFloat = testFloat;
	}
	public java.lang.Float getTestFloat(){
		return this.testFloat;
	}
	public void setTestDecimal(java.lang.Double testDecimal){
		this.testDecimal = testDecimal;
	}
	public java.lang.Double getTestDecimal(){
		return this.testDecimal;
	}
	public void setTestDate(java.util.Date testDate){
		this.testDate = testDate;
	}
	public java.util.Date getTestDate(){
		return this.testDate;
	}
	public void setTestDatetime(java.util.Date testDatetime){
		this.testDatetime = testDatetime;
	}
	public java.util.Date getTestDatetime(){
		return this.testDatetime;
	}
	
	

}