package com.thd.common.infrastructure.pojo;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * com.thd.common.infrastructure.pojo.SysDicPubClassify entity. 
 * file autogenerated by ThirdteenDevils's CodeGenUtil
 */
@Entity
@Table(name="sys_dic_pub_classify")
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class SysDicPubClassify implements java.io.Serializable {
	//PK  主键
	@Id
	@GenericGenerator(name = "idGeneratorForSysDicPubClassify", strategy = "assigned")  
	@GeneratedValue(generator = "idGeneratorForSysDicPubClassify")
	@Column(name="classify_id" ,length=50)
	private java.lang.String classifyId;
	
	
	
	
	//分类名称
	//varchar
	@Column(name="classify_name" ,length=20)
	private java.lang.String classifyName;
	
	//分类备注
	//varchar
	@Column(name="classify_desc" ,length=255)
	private java.lang.String classifyDesc;
	
	//创建时间
	//datetime
	//@Temporal(TemporalType.TIMESTAMP)
	@JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
	@Column(name="cre_time" )
	private java.util.Date creTime;
	
	//创建人
	//int
	@Column(name="cre_user" )
	private java.lang.Integer creUser;
	
	//修改时间
	//date
	//@Temporal(TemporalType.DATE)
	@JsonFormat(pattern="yyyy-MM-dd",timezone="GMT+8")
	@Column(name="mod_time" )
	private java.util.Date modTime;
	
	//修改人
	//float
	@Column(name="mod_user" )
	private java.lang.Float modUser;
	
	
	public void setClassifyId(java.lang.String classifyId){
		this.classifyId = classifyId;
	}
	public java.lang.String getClassifyId(){
		return this.classifyId;
	}
	public void setClassifyName(java.lang.String classifyName){
		this.classifyName = classifyName;
	}
	public java.lang.String getClassifyName(){
		return this.classifyName;
	}
	public void setClassifyDesc(java.lang.String classifyDesc){
		this.classifyDesc = classifyDesc;
	}
	public java.lang.String getClassifyDesc(){
		return this.classifyDesc;
	}
	public void setCreTime(java.util.Date creTime){
		this.creTime = creTime;
	}
	public java.util.Date getCreTime(){
		return this.creTime;
	}
	public void setCreUser(java.lang.Integer creUser){
		this.creUser = creUser;
	}
	public java.lang.Integer getCreUser(){
		return this.creUser;
	}
	public void setModTime(java.util.Date modTime){
		this.modTime = modTime;
	}
	public java.util.Date getModTime(){
		return this.modTime;
	}
	public void setModUser(java.lang.Float modUser){
		this.modUser = modUser;
	}
	public java.lang.Float getModUser(){
		return this.modUser;
	}
	
	

}