package com.thd.common.infrastructure.pojo;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * com.thd.common.infrastructure.pojo.SysDicPub entity. 
 * file autogenerated by ThirdteenDevils's CodeGenUtil
 */
@Entity
@Table(name="sys_dic_pub")
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class SysDicPub implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;




	//PK  字典标识
	@Id
	//@GenericGenerator(name = "idGeneratorForSysDicPub", strategy = "uuid.hex") 
	@GenericGenerator(name = "idGeneratorForSysDicPub", strategy = "assigned") 
	@GeneratedValue(generator = "idGeneratorForSysDicPub") 
	@Column(name="dic_id" ,length=50)
	private java.lang.String dicId;
	
	
	
	
	//字典分类
	//varchar
	@Column(name="dic_classify" ,length=50)
	private java.lang.String dicClassify;
	
	//字典名称
	//varchar
	@Column(name="dic_name" ,length=50)
	private java.lang.String dicName;
	
	//备注
	//varchar
	@Column(name="dic_desc" ,length=500)
	private java.lang.String dicDesc;
	







	
	public void setDicId(java.lang.String dicId){
		this.dicId = dicId;
	}
	public java.lang.String getDicId(){
		return this.dicId;
	}
	public void setDicClassify(java.lang.String dicClassify){
		this.dicClassify = dicClassify;
	}
	public java.lang.String getDicClassify(){
		return this.dicClassify;
	}
	public void setDicName(java.lang.String dicName){
		this.dicName = dicName;
	}
	public java.lang.String getDicName(){
		return this.dicName;
	}
	public void setDicDesc(java.lang.String dicDesc){
		this.dicDesc = dicDesc;
	}
	public java.lang.String getDicDesc(){
		return this.dicDesc;
	}
	
	

}