package com.thd.common.infrastructure.pojo;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * cn.thd.pojo.se.SysUser entity. 
 * file autogenerated by ThirdteenDevils's CodeGenUtil
 */
@Entity
@Table(name="sys_user")
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class SysUser implements java.io.Serializable {
	//PK  用户ID
	@Id
	@GenericGenerator(name = "idGeneratorForSysUser", strategy = "assigned")  
	@GeneratedValue(generator = "idGeneratorForSysUser") 
	@Column(name="user_id" ,length=50)
	private java.lang.String userId;
	
	
	
	
	//用户姓名
	//varchar
	@Column(name="user_name" ,length=50)
	private java.lang.String userName;
	
	//
	//varchar
	@Column(name="user_account" ,length=50)
	private java.lang.String userAccount;
	
	//
	//varchar
	@Column(name="user_password" ,length=50)
	private java.lang.String userPassword;
	
	//所在公司
	//varchar
	@Column(name="company_name" ,length=200)
	private java.lang.String companyName;
	
	//邮箱
	//varchar
	@Column(name="user_mail" ,length=100)
	private java.lang.String userMail;
	
	//
	//date
	@Temporal(TemporalType.DATE)
	@Column(name="user_birthday" )
	private java.util.Date userBirthday;
	
	//
	//varchar
	@Column(name="user_tel" ,length=50)
	private java.lang.String userTel;
	
	//
	//varchar
	@Column(name="user_sex" ,length=10)
	private java.lang.String userSex;
	
	//
	//datetime
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="cre_time" )
	private java.util.Date creTime;
	
	//
	//varchar
	@Column(name="cre_user" ,length=50)
	private java.lang.String creUser;
	
	//
	//datetime
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="mod_time" )
	private java.util.Date modTime;
	
	//
	//varchar
	@Column(name="mod_user" ,length=50)
	private java.lang.String modUser;
	







	
	public void setUserId(java.lang.String userId){
		this.userId = userId;
	}
	public java.lang.String getUserId(){
		return this.userId;
	}
	public void setUserName(java.lang.String userName){
		this.userName = userName;
	}
	public java.lang.String getUserName(){
		return this.userName;
	}
	public void setUserAccount(java.lang.String userAccount){
		this.userAccount = userAccount;
	}
	public java.lang.String getUserAccount(){
		return this.userAccount;
	}
	public void setUserPassword(java.lang.String userPassword){
		this.userPassword = userPassword;
	}
	public java.lang.String getUserPassword(){
		return this.userPassword;
	}
	public void setCompanyName(java.lang.String companyName){
		this.companyName = companyName;
	}
	public java.lang.String getCompanyName(){
		return this.companyName;
	}
	public void setUserMail(java.lang.String userMail){
		this.userMail = userMail;
	}
	public java.lang.String getUserMail(){
		return this.userMail;
	}
	public void setUserBirthday(java.util.Date userBirthday){
		this.userBirthday = userBirthday;
	}
	public java.util.Date getUserBirthday(){
		return this.userBirthday;
	}
	public void setUserTel(java.lang.String userTel){
		this.userTel = userTel;
	}
	public java.lang.String getUserTel(){
		return this.userTel;
	}
	public void setUserSex(java.lang.String userSex){
		this.userSex = userSex;
	}
	public java.lang.String getUserSex(){
		return this.userSex;
	}
	public void setCreTime(java.util.Date creTime){
		this.creTime = creTime;
	}
	public java.util.Date getCreTime(){
		return this.creTime;
	}
	public void setCreUser(java.lang.String creUser){
		this.creUser = creUser;
	}
	public java.lang.String getCreUser(){
		return this.creUser;
	}
	public void setModTime(java.util.Date modTime){
		this.modTime = modTime;
	}
	public java.util.Date getModTime(){
		return this.modTime;
	}
	public void setModUser(java.lang.String modUser){
		this.modUser = modUser;
	}
	public java.lang.String getModUser(){
		return this.modUser;
	}
	
	

}