package com.thd.module.note.pojo;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * com.thd.module.note.pojo.ModNoteContent entity. 
 * file autogenerated by ThirdteenDevils's CodeGenUtil
 */
@Entity
@Table(name="mod_note_content")
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class ModNoteContent implements java.io.Serializable {
	//PK  主键
	@Id
	@GenericGenerator(name = "idGeneratorForModNoteContent", strategy = "assigned")  
	@GeneratedValue(generator = "idGeneratorForModNoteContent")
	@Column(name="note_id" ,length=50)
	private java.lang.String noteId;
	
	
	
	
	//记事内容
	//text
	@Column(name="note_content" )
	private java.lang.String noteContent;
	







	
	public void setNoteId(java.lang.String noteId){
		this.noteId = noteId;
	}
	public java.lang.String getNoteId(){
		return this.noteId;
	}
	public void setNoteContent(java.lang.String noteContent){
		this.noteContent = noteContent;
	}
	public java.lang.String getNoteContent(){
		return this.noteContent;
	}
	
	

}